### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by doughardy-ctnj** [mzagaja/ctnewsjunkie_voterguide#115]
Is this error specific to photo size or is it possible that it's related to something else like amount of text in a survey field?

If it's the photo file size, we can probably tell people to make sure images are less than 300kb or something.

**Comment by doughardy-ctnj** [comment]
A couple of people have gotten this error so I assumed it was photo size. Last one had tried to load a photo file that was 3.7MB

**Comment by mzagaja** [comment]
I think its a configuration limitation of nginx. I just updated it so try again with a photo and let me know.

**Comment by doughardy-ctnj** [comment]
fixed - nice work
