### ISSUE TITLE
Prettify District Index Page

### ISSUE THREAD

**Issue by mzagaja** [mzagaja/ctnewsjunkie_voterguide#13]
Was thinking some kind of grid of district numbers with a creative commons picture of some sort that represents that district. Lots of work to source all the pictures so might not be able to do that, or maybe I can automate it with Flickr or Wikipedia Commons.

**Comment by doughardy-ctnj** [comment]
ideally a map outline of the district but i don't know what they are easily
available. other images will be all over the place in terms of availability
or quality. they don't all have an image for sure.

*Doug Hardy*
Business Manager, Dig and Scoop LLC dba CTNewsJunkie.com
<http://ctnewsjunkie.com/>
Co-Founder/New Media Developer for Independent Media Network LLC
<http://imnct.com/>
(860) 543-9453 (mobile)

**Comment by mzagaja** [comment]
Ok made some updates on this so it is now closer to what I was thinking. I want to make it so that the entire boxes are clickable and not just the district numbers. The candidates page has also similarly been updated.

**Comment by mzagaja** [comment]
Also this is live on the staging site if you want to take a look on your phone: https://enigmatic-escarpment-35887.herokuapp.com
