### ISSUE TITLE
Add Polling Feature

### ISSUE THREAD

**Issue by mzagaja** [mzagaja/ctnewsjunkie_voterguide#15]
Should people be able to vote in a single poll or in each district?
How should the interface work? Do we include a button in the partial for the candidate that says "I support this candidate" or something at the top of the district page? Need to play with this.
Once people vote they cannot vote again, but maybe they can change their vote.
Should we require e-mail to vote?

**Comment by doughardy-ctnj** [comment]
>
> Should people be able to vote in a single poll or in each district?
>
Should it be their ballot or should we be polling based on their specific
candidates and that's it - meaning local candidates, not presidential.
Might be good to have presidential. Let me know what you think.

> How should the interface work? Do we include a button in the partial for
> the candidate that says "I support this candidate" or something at the top
> of the district page? Need to play with this.
>
The more it looks like a ballot the better, no?

> Once people vote they cannot vote again, but maybe they can change their
> vote.
> Should we require e-mail to vote?
>
Requiring a unique email to vote will go a long way toward reducing fraud,
I would think. Better than just allowing to clear cache and open a private
window

**Comment by mzagaja** [comment]
Been thinking about this today. I don't think a ballot is the right UI for this because we do not have a fixed size piece of paper we need to design for, but rather a range of devices with multiple sizes. Presidential candidate preferences could be interesting but I think that can be tacked on later.

**Comment by mzagaja** [comment]
This feature is almost ready. I just need to get the forms working correctly to submit the votes.

Note to self: http://railscasts.com/episodes/196-nested-model-form-part-1

Also will need to do following:

- [ ] Add logic to prompt users to sign-in if they have not signed in and attempt to vote
- [ ] Restrict vote to one per account
- [ ] Allow users to change their vote

**Comment by mzagaja** [comment]
Ok initial commit of this feature is now in and deployed to the production site.

**Comment by mzagaja** [comment]
Ok this is set for now. Any updates can be new issues.
