### ISSUE TITLE
Shade Districts Based on Who is Winning

### ISSUE THREAD

**Issue by mzagaja** [mzagaja/ctnewsjunkie_voterguide#16]
Maybe in the next release we can shade or somehow indicate in each district who is winning in the CTNJ online poll.

**Comment by doughardy-ctnj** [comment]
good thought

*Doug Hardy*
Business Manager, Dig and Scoop LLC dba CTNewsJunkie.com
<http://ctnewsjunkie.com/>
Co-Founder/New Media Developer for Independent Media Network LLC
<http://imnct.com/>
(860) 543-9453 (mobile)
