### ISSUE TITLE
Add Analytics

### ISSUE THREAD

**Issue by mzagaja** [mzagaja/ctnewsjunkie_voterguide#18]
Do we need Google Analytics on here? If so let me know what ID/HTML to use. I am going to also include New Relic for basic monitoring. If we need any other analytics let me know.

**Comment by doughardy-ctnj** [comment]
Glad you asked, I will get you GA and Quantcast. Need to add them to
directory as well :-/

**Comment by doughardy-ctnj** [comment]
I'm not sure whether I should just provide the same Google Analytics code that we use for CTNewsJunkie or a separate setup.

**Comment by doughardy-ctnj** [comment]
I think I added a GA account:
UA-85362087-1

We can add Quantcast once we're up

**Comment by doughardy-ctnj** [comment]
[google analytics universal analytics tracking code.txt](https://github.com/mzagaja/ctnewsjunkie_voterguide/files/518085/google.analytics.universal.analytics.tracking.code.txt)

**Comment by mzagaja** [comment]
Google analytics is live.

**Comment by doughardy-ctnj** [comment]
Here's Quantcast tag instructs:

In the HTML code of every webpage of your site, place the following code (attached) just before the </body> tag and any other measurement tags. For additional help please see our [Web Measurement Implementation Guide](https://www.quantcast.com/help/guides/web-measurement-implementation-guide/).
[Quantcast_Tag.txt](https://github.com/mzagaja/ctnewsjunkie_voterguide/files/518748/Quantcast_Tag.txt)
