### ISSUE TITLE
HTML 5 Geolocation

### ISSUE THREAD

**Issue by mzagaja** [mzagaja/ctnewsjunkie_voterguide#2]
Integrate the HTML 5 Geolocation Feature to send users to their relevant house or senate district when they click a button.

**Comment by mzagaja** [comment]
Issues Discovered so Far in Implementation:

- [ ] Edge case of users outside CT trying to use Geolocation throws bad data. Need a friendly error message if you're outside CT.
- [ ] House and senate districts are separate buttons with separate hidden tag fields. Need to change javascript to apply location to both house and senate buttons
- [ ] Add appropriate automated tests
- [ ] Update to search for appropriate house or senate district using the text fields instead of the database id column

**Comment by mzagaja** [comment]
Maybe consider [IP location](https://www.maxmind.com/en/geoip2-precision-services) as a fallback followed by user entered zip code.

**Comment by doughardy-ctnj** [comment]
Voting districts don't coincide with zip codes though

**Comment by mzagaja** [comment]
You're right we'll have to use a solution that uses full street addresses. Looking into use of https://github.com/alexreisner/geocoder in order to implement something more robust. Maybe can spike a quicker solution using the Open Street Map API http://wiki.openstreetmap.org/wiki/Nominatim

**Comment by doughardy-ctnj** [comment]
Should I reach out to Nimit and see if we can access his api? We'll need to
sign nondiscolsure
