### ISSUE TITLE
Register to Vote feature

### ISSUE THREAD

**Issue by doughardy-ctnj** [mzagaja/ctnewsjunkie_voterguide#21]
We have this action center set up: https://p2a.co/eJgCodH

I'm still waiting to hear from them about logging in and getting an embed that we could use on the site.

**Comment by doughardy-ctnj** [comment]
Here's the embed code:

<div class="civicactioncenter-widget" data-domain="p2a.co" data-shorturl="99b6T54"  style="width: 100%; height: 100%;"></div>
<script>
    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = '//p2a.co/js/embed/widget/civicactioncenter.widget.js';
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'civicactioncenter-code'));
</script>

**Comment by mzagaja** [comment]
Can you describe where you want this to live? Should we embed it or link it? Does it get its own link/page on the menu bar?

**Comment by doughardy-ctnj** [comment]
Menu bar and maybe some prominence on arrival. Maybe the embed works or it
doesn't.
