### ISSUE TITLE
thoughts on the home page?

### ISSUE THREAD

**Issue by doughardy-ctnj** [mzagaja/ctnewsjunkie_voterguide#22]
It's a long list that just says State Representative and a numeral that's linked. Do we want to do an outline of the district with town names in it? Or will that load super slowly?

**Comment by mzagaja** [comment]
I'm not opposed to the idea but I would need a source of the district images and a CSV of the town names for each district in order to do this.

**Comment by doughardy-ctnj** [comment]
sounds good - i'll see what i can find

*Doug Hardy*
Business Manager, Dig and Scoop LLC dba CTNewsJunkie.com
<http://ctnewsjunkie.com/>
Co-Founder/New Media Developer for Independent Media Network LLC
<http://t.sidekickopen06.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1qg6yjW65jFwx2BG1rjW7fZnDC56dTLff5RwnrT02?t=http%3A%2F%2Fimnct.com%2F&si=6455957142372352&pi=d4085083-cf6f-4fcb-ae9c-774a1779374e>
(860) 543-9453 (mobile)

**Comment by doughardy-ctnj** [comment]
If I could get you the image files, how wide/tall and file size?

**Comment by mzagaja** [comment]
250px wide by whatever height makes sense is probably good.

**Comment by doughardy-ctnj** [comment]
OK thanks. I started trying to carve districts out of a larger map last
night and realized it's a long project - probly can't pull it off. If you
have any thoughts about dressing up the home page I'd be open to
suggestions. It's fine for now.

*Doug Hardy*
Business Manager, Dig and Scoop LLC dba CTNewsJunkie.com
<http://ctnewsjunkie.com/>
Co-Founder/New Media Developer for Independent Media Network LLC
<http://t.sidekickopen06.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1qg6yjW65jFwx2BG1rjW7fZnDC56dTLff5RwnrT02?t=http%3A%2F%2Fimnct.com%2F&si=6455957142372352&pi=a4a24389-62b3-4c8f-e2e6-1f0d886a8523>
(860) 543-9453 (mobile)

**Comment by mzagaja** [comment]
Might be able to put a map of the districts and shade it based on the current votes. But not sure how ready for launch it'd be as it could be more complicated than I expect. Maybe just throw and image in there somewhere? Also keeping in mind another iteration is supposed to have an option to enter your address to get your reps and senators.

**Comment by doughardy-ctnj** [comment]
Rather than an image maybe let's try making the district number a lot bigger to fill that white space a bit?

**Comment by mzagaja** [comment]
Ok I tried converting it to ordinals and changing font sizes. Take a look let me know what you think.

**Comment by doughardy-ctnj** [comment]
looks a better thanks

maybe we could just list towns for each district. i'll give it some thought. i think the visual presentation is probably less important than I'm thinking for the home page but i'll keep thinking.

**Comment by mzagaja** [comment]
I don't think it's worth spending too much effort on this since it is easily changed after launch and people are less likely to bother with these than the automatic district chooser feature. The towns idea probably is a good one but I would need a CSV source of that data.

**Comment by doughardy-ctnj** [comment]
ok i'll ask for a csv as well on that but let's move on
