### ISSUE TITLE
Endorsement/sharing vs voting

### ISSUE THREAD

**Issue by doughardy-ctnj** [mzagaja/ctnewsjunkie_voterguide#23]
I have a thought - i don't think the voting thing has much potential but an "endorse" button might be good or a pair of them - one for FB and one for Twitter. They click and they are sharing an "I am endorsing XYZ for House/Senate District X."

My thinking is, the value of the faux poll of voting is lower than the value of a lot of people clicking "endorse" and having that appear on social media with them sharing the page.

**Comment by mzagaja** [comment]
I think we have them click the vote button (but change the text to endorse) and then we can present them with a social sharing option at the next page or in a pop-up or something.

**Comment by doughardy-ctnj** [comment]
Agree - it should share with some automatic text inserted "I am endorsing X" with a link to the individual's Q&A

**Comment by mzagaja** [comment]
I'm going to have to punt this to the weekend as it looks like it might be decently substantial task.

**Comment by doughardy-ctnj** [comment]
OK no problem - thanks for all this effort. I know I'm sending a lot of requests. I think it's going to be a cool product.

**Comment by doughardy-ctnj** [comment]
What do you think of dumping the voter registration aspect for now and just creating "endorse this candidate" buttons for social sharing?

**Comment by mzagaja** [comment]
Ultimately I think it's better to collect user registrations/e-mails no matter how we phrase it. I think the polling would be stickier and give people a reason to convince people to get their friends to sign up. We can phrase it as endorsements but present it the way we'd present a poll and say like "more people have endorsed this candidate than this other candidate" and still have the same effect. I think if we replaced the voting with social sharing it might not be used as much.

**Comment by doughardy-ctnj** [comment]
OK good thoughts. Can't disagree. Are we going to be able to do that tonight for a push to the campaigns tomorrow?

**Comment by mzagaja** [comment]
Tomorrow night I should be able to change the text to endorse and then try and write the script to do the e-mail.

**Comment by doughardy-ctnj** [comment]
ok thanks
