### ISSUE TITLE
header and menu items

### ISSUE THREAD

**Issue by doughardy-ctnj** [mzagaja/ctnewsjunkie_voterguide#25]
I may try to redo the header to say "VOTE.CTNEWSJUNKIE.COM" ... just hopeful I can even survive this weekend in terms of stuff piling up.

Menu items ... left to right:

News - http://www.ctnewsjunkie.com/
The Directory - http://directory.ctnewsjunkie.com/
About - I need an about page for vote.ctnewsjunkie.com/about - should I build this in WP?
Sponsorship - vote.ctnewsjunkie.com/sponsorship
Contact - http://www.ctnewsjunkie.com/contact/
Join the Club - https://directory.ctnewsjunkie.com/support_public_service_journalism/
Email Sign-Up - http://www.ctnewsjunkie.com/archives/page/sign_up_for_our_email_blasts/

**Comment by doughardy-ctnj** [comment]
OK here's the new header - it's 970x180.
![vote-ctnewsjunkie-header-logo-10-21-16](https://cloud.githubusercontent.com/assets/22284125/19609342/9d90434c-97a4-11e6-9005-0952d696c13d.jpg)

**Comment by mzagaja** [comment]
For about and sponsorship just give me the content and I'll create static pages for them.

**Comment by doughardy-ctnj** [comment]
Can you just make the header image fill the whole space rather than the orange deadspace?

I know you have some share buttons up there, but those could go down in menu bar maybe

**Comment by mzagaja** [comment]
I can but you'll need to make the actual image file wider in however you want it to look. The height is locked in.

**Comment by doughardy-ctnj** [comment]
About page

Welcome to the CTNewsJunkie's latest addition - Vote.CTNewsJunkie.com - a Voter Guide and Candidate Questionnaire.

This site is here as a service to candidates who need to get their message out, and to voters who need to learn more about candidates in order to make an informed decision.

It's got a lot of bells and whistles, so to speak. We've included an option to check your voter registration, find out who all of your candidates are locally using geolocation, locate your polling place, and also to start the process of registering to vote and/or vote absentee.

But the goal here is to get as much participation as possible from all the candidates, and then to push their answers out to as many readers as possible. Help us out by sharing your District pages on your social networks!

We're launching this site pretty late in the election season and hope to iron out as many bugs as possible so that we can make spectacular use of it in the next election. Let us know if you're having any problems on the site.

And our gratitude goes out to Matt Zagaja, who basically built this thing from scratch based on a few loosely organized ideas. Thanks Matt!

-Christine Stuart

**Comment by doughardy-ctnj** [comment]
Sponsorship page:

If you or your organization would like to sponsor this project, we're happy to oblige.

You can sponsor one or more questions to the entire field of incumbents and challengers, or you can become an umbrella sponsor.

![image](https://cloud.githubusercontent.com/assets/22284125/19616696/2892b086-97e8-11e6-8e2f-6e535a16e923.png)

[**Contact us**](http://www.ctnewsjunkie.com/contact/) if you have questions or need more information. We're still working out details in terms of SEEC compliance, but we plan to provide appropriate disclaimer and compliance language at the bottom of the site to cover all the bases. If you're an organization that accepts political donations, you'll need to provide us with your top five donors to meet SEEC regulations.

More to come on this - thanks for your patience and support!

**Comment by doughardy-ctnj** [comment]
Can you limit the site to 970 wide or would that be counter-productive in terms of responsive design?

**Comment by mzagaja** [comment]
Probably another week or two of work to refactor the site to look good at that width and have everything working ok if I try that.

**Comment by doughardy-ctnj** [comment]
OK, I'll see if I can create a wider version - what's the maximum height?

**Comment by doughardy-ctnj** [comment]
![vote-ctnewsjunkie-horizontal-header-logo-1170x90-text-only-10-21-16](https://cloud.githubusercontent.com/assets/22284125/19617019/a57686a4-97f2-11e6-9b3f-b6901c2d7fab.jpg)

![vote-ctnewsjunkie-horizontal-header-logo-1170x90-pins3-10-21-16](https://cloud.githubusercontent.com/assets/22284125/19617020/acf9bea0-97f2-11e6-9885-932a871f5a67.jpg)

![vote-ctnewsjunkie-horizontal-header-logo-1170x90-pins2-10-21-16](https://cloud.githubusercontent.com/assets/22284125/19617025/bb216208-97f2-11e6-8478-bb3ac9bb9656.jpg)

![vote-ctnewsjunkie-horizontal-header-logo-1170x90-pins1-10-21-16](https://cloud.githubusercontent.com/assets/22284125/19617028/c817081e-97f2-11e6-8017-db5d7865e1f5.jpg)

**Comment by doughardy-ctnj** [comment]
I like either the second or third ones...

**Comment by mzagaja** [comment]
I like the third one. I realized that these don't scale down that well so I may try and see if I can switch from the large one to the smaller version when people use tablets, etc. I think I may have some time tonight. Not sure how late my friends are staying but am heading out in a little bit.

**Comment by doughardy-ctnj** [comment]
Yeah i kind of like the idea of spelling out the subdomain.

Question - in the current config, can we load the red-white-blue pin image as the background to the header container (instead of orange), so that it looks like #3 on the desktop, but when the window shrinks it'll eventually use just the header portion?

**Comment by doughardy-ctnj** [comment]
here's an optimized version - 53kb:

![vote-ctnewsjunkiel-header-logo-1170x90-pins2-optimized-10-21-16](https://cloud.githubusercontent.com/assets/22284125/19620043/21a7f768-9842-11e6-855a-909eab4d27f7.jpg)

**Comment by mzagaja** [comment]
Yeah that should work, just send me the separated red white blue vote image.

**Comment by doughardy-ctnj** [comment]
ok that sounds good - it would have to be the full width at 1170 by 90, right? Or would it be just the portion on the right?

**Comment by doughardy-ctnj** [comment]
here's the full high-res image - assuming you want me to narrow it to 90px tall or 180?
![vote-pins-shutterstock_376847752](https://cloud.githubusercontent.com/assets/22284125/19620061/891f675a-9842-11e6-8c85-f211595cdbea.jpg)

**Comment by mzagaja** [comment]
I'll dial in the size. At some point need to set up images to optimize for retina displays with different assets, etc. anyways.

**Comment by doughardy-ctnj** [comment]
OK... I tilted the image a bit - here's the version with the tilt:
![vote-pins-tilted-shutterstock_376847752](https://cloud.githubusercontent.com/assets/22284125/19620129/fc07ec00-9843-11e6-8bec-656acd43c4e0.jpg)

**Comment by mzagaja** [comment]
180px
