### ISSUE TITLE
Disclaimer language UPDATED

### ISSUE THREAD

**Issue by doughardy-ctnj** [mzagaja/ctnewsjunkie_voterguide#26]
Just got off the phone with the SEEC's compliance attorney, Josh Foley. They see these sponsored questions as political messages

So we need to add some blanket language at the bottom of the page on which the questions appear that cover the required vergiage for independent expenditures. We'll need a blurb for each sponsor - but something like this:

**Questions 1, 2, 3 were paid for by AARP Connecticut. The messages in these questions were made independent of any candidate or political party. _(((***Then we need the names of the five persons who made the five largest aggregate covered transfers to the AARP during the 12-month period immediately prior to such primary or election, as applicable -- but we don't need to list any if there were no contributors of more than $5K. ****)))_ Additional information may be found on the State Elections Enforcement Commission’s web site.**

**Comment by doughardy-ctnj** [comment]
I will need to nail down the exact language though but you might as well put in the placeholder if you get a chance

**Comment by mzagaja** [comment]
Does this need to be in the footer of the page displayed to candidates, the page displayed to users, or both?

**Comment by doughardy-ctnj** [comment]
hold off for now - but yeah if we have to use it, likely the footer would work

**Comment by mzagaja** [comment]
Let me know where we land on this and I'll toss it in.

**Comment by doughardy-ctnj** [comment]
working on it now

**Comment by doughardy-ctnj** [comment]
Disclaimer language:

## This product is for research only. CTNewsJunkie does not endorse any legislation referenced on this site or candidates for office.

## Questions 4, 5, 6 were paid for by AARP Connecticut. The messages in these questions were made independent of any candidate or political party. AARP Connecticut does not endorse candidates.

## Additional information may be found on the State Elections Enforcement Commission’s web site.

**Comment by doughardy-ctnj** [comment]
think you can shade the background of the disclaimer to make it stand out a bit, maybe space it down another line or two away from the rest of the content?

**Comment by doughardy-ctnj** [comment]
Think you can update the disclaimer language tonight and change the "vote for this candidate" buttons to "endorse this candidate"?

In terms of endorsing... I'm actually thinking these should just be share buttons, and we don't need to fight with the voter registration lists. Agree?

After that, we're ready to have AARP look at it once more and then push it out to the candidates.

**Comment by mzagaja** [comment]
Updated
