### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by doughardy-ctnj** [mzagaja/ctnewsjunkie_voterguide#29]
I'm hoping to get a few more questions and hopefully another sponsor over the weekend - it's highly doubtful though. 

But I'm going to have christine look over the questions and maybe we'll want to re-order them. There's a high probability that AARP will walk away on Monday, so we may have to pull their logo. I may leave their questions in there, however, without attribution, just in this beta model. 

Thanks your efforts tonight - feeling a lot better with respect to how close we are.

**Comment by mzagaja** [comment]
That's a shame, I thought their questions were good.

**Comment by doughardy-ctnj** [comment]
Agree - it's terrible. They are big supporters of our efforts here, but it's a national organization that's actually paying for things, and the CT director says there's no way they'd get donor information. It would be people from other states. SEEC has really been problematic on many levels the last few years, with respect to overreach.

Best thing to do right now would be to leave the questions in but nix the logos and "sponsored by" language for now. 

I'm wondering if maybe the smart thing to do for now would be to put a face on each question, rather than a brand. Terry Cowgill asked one of them, Jack Kramer another - people from CTNJ. What do you think?

**Comment by mzagaja** [comment]
In general I think it's better to keep them faceless because candidates may react to them differently knowing who asked. The org has a bit more authority. If we don't get sponsors we can always just remove that section/language.

Any luck getting in touch with NationBuilder about doing a general sponsorship of the concept?

**Comment by doughardy-ctnj** [comment]
I did one bulk outreach to all of our clients in CT but never got around to trying NationBuilder - I think it's a good idea. I'll

**Comment by doughardy-ctnj** [comment]
Will McConway at NationBuilder is a former ct.gov person on the Republican side... he may be a good connection. I'll try him. Otherwise it's a blind email to their info@ email address.

**Comment by doughardy-ctnj** [comment]
Also - we definitely need to strip out the AARP icons (make the ctnj squares) and the "sponsored by" line above the questions.

They may yet agree to let us make them a generic sponsor of the whole thing, but we'll see how it goes.

**Comment by mzagaja** [comment]
I reverted this to have the AARP questions again per the e-mail conversation.

**Comment by doughardy-ctnj** [comment]
Disclaimer language:

## This product is for research only. CTNewsJunkie does not endorse any legislation referenced on this site or candidates for office.

## Questions 4, 5, 6 were paid for by AARP Connecticut. The messages in these questions were made independent of any candidate or political party. AARP Connecticut does not endorse candidates. 

## Additional information may be found on the State Elections Enforcement Commission’s web site.
