### ISSUE TITLE
Image Attachments

### ISSUE THREAD

**Issue by mzagaja** [mzagaja/ctnewsjunkie_voterguide#3]
Enable image attachments.

**Comment by mzagaja** [comment]
Initial image attachments feature has been completed but will need to be tweaked to work with the eventual front-end setup. Specifically in relation to image sizes. It also needs to be tested.

**Comment by doughardy-ctnj** [comment]
Sweet - yeah we'll need to dial in dimensions with some kind of flexibility
if it's easy, crop or whatever
