### ISSUE TITLE
Header image

### ISSUE THREAD

**Issue by doughardy-ctnj** [mzagaja/ctnewsjunkie_voterguide#32]
what was the exact size of the header image you ended up using? I'd like to adjust it a bit - the main "vote" button is to close to center and gets cut off on desktop.

**Comment by mzagaja** [comment]
It is at https://github.com/mzagaja/ctnewsjunkie_voterguide/blob/master/app/assets/images/header-background.jpg

**Comment by doughardy-ctnj** [comment]
i don't think i can commit changes

here's the new image:
![header-background](https://cloud.githubusercontent.com/assets/22284125/19671553/8d3a12d4-9a3d-11e6-9084-eae9bd479055.jpg)
