### ISSUE TITLE
fixing typo on About page

### ISSUE THREAD

**Issue by doughardy-ctnj** [mzagaja/ctnewsjunkie_voterguide#33]
I made a change here:
https://github.com/mzagaja/ctnewsjunkie_voterguide/blob/master/app/views/pages/about.html.erb

But haven't seen it show up yet. Is there another location to change for the About page as well?

**Comment by mzagaja** [comment]
When you make a change on GitHub it does not reflect on the main website until I manually deploy it.

**Comment by doughardy-ctnj** [comment]
Ok -to reorder questions can i just change the numbers in the q1 or move
sections around?

**Comment by mzagaja** [comment]
Move the actual question text to where you want it. Everything else stays the same. 

-Matt

**Comment by mzagaja** [comment]
Looking at the commit history tonight it looks like you changed the q1, q2, etc. which has no impact on how the questions are displayed. You need to move the actual question text in the document around, not the number references, those should stay put.

**Comment by doughardy-ctnj** [comment]
yeah i believe i switched it back - will do it the right way in a few. 

i'll look again - but moving the icons with the right questions?
