### ISSUE TITLE
Ad tag issue maybe

### ISSUE THREAD

**Issue by doughardy-ctnj** [mzagaja/ctnewsjunkie_voterguide#35]
have you seen this popup?
![screen shot 2016-10-27 at 3 28 31 pm](https://cloud.githubusercontent.com/assets/22284125/19782078/3f55d372-9c5a-11e6-873c-b09c07f9c3a4.png)

I'm checking on it

**Comment by mzagaja** [comment]
I haven't seen it, but are you running an ad blocker of some sort in your browser? Those can mess with the code.

**Comment by doughardy-ctnj** [comment]
Me? Never. I will never run an ad blocker. I pinged Broadstreet about it.

*Doug Hardy*
Business Manager, Dig and Scoop LLC dba CTNewsJunkie.com
<http://ctnewsjunkie.com/>
Co-Founder/New Media Developer for Independent Media Network LLC
<http://t.sidekickopen06.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1qg6yjW65jFwx2BG1rjW7fZnDC56dTLff5RwnrT02?t=http%3A%2F%2Fimnct.com%2F&si=6455957142372352&pi=6c928200-a7f8-4abc-d8f1-ae1a47640021>
(860) 543-9453 (mobile)

**Comment by doughardy-ctnj** [comment]
Kenny Katzgrau <https://www.facebook.com/katzgrau?fref=ufi> Hrm. In the ad
tag, you'll see a line like:

js.async = true;

Want to try setting that to this?

js.async = false;

Just a hunch, but it would be strange since there's never been an issue w/
that before.

*Doug Hardy*
Business Manager, Dig and Scoop LLC dba CTNewsJunkie.com
<http://ctnewsjunkie.com/>
Co-Founder/New Media Developer for Independent Media Network LLC
<http://t.sidekickopen06.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XYg1qg6yjW65jFwx2BG1rjW7fZnDC56dTLff5RwnrT02?t=http%3A%2F%2Fimnct.com%2F&si=6455957142372352&pi=626c5a80-0f17-401a-a36c-d6a2a2e34550>
(860) 543-9453 (mobile)

**Comment by mzagaja** [comment]
What browser is this in? Mine is doing ok in Chrome.

**Comment by doughardy-ctnj** [comment]
it was chrome

**Comment by mzagaja** [comment]
Weird. Well I just pushed the suggested change. Give it 2 minutes and then do a CMD+Refresh.

**Comment by doughardy-ctnj** [comment]
OK will do ...

To generate the error, I visit the home page, then click to a district page - and then hit the back button to home, and i get the error 

on the topic of using the back button, it would be good to have the header click through to vote.ctnewsjunkie.com

**Comment by doughardy-ctnj** [comment]
Looks like the "false" change didn't stop the error. I'll tell Kenny at Broadstreet.

**Comment by doughardy-ctnj** [comment]
I may just change it to a static 970x250. Could be the java
