### ISSUE TITLE
Account Creation Fails on Duplicate E-Mails

### ISSUE THREAD

**Issue by mzagaja** [mzagaja/ctnewsjunkie_voterguide#37]
Candidate accounts fail to be created due to some duplicate e-mails, which shouldn't happen generally since each candidate should have their own e-mail so I need to dig into this further to identify the troublemaker outliers.

**Comment by doughardy-ctnj** [comment]
ok thanks

I know you're working at this pretty hard but we're definitely running out of time - if you have to gerry rig something or reduce the scope of this piece considerably to get this out the door, it's worth considering. i told the sponsor it would be ready oct 28.

**Comment by mzagaja** [comment]
Ok I will try and see if I can sneak some time on this at lunch time tomorrow then if we're working on deadline.

**Comment by doughardy-ctnj** [comment]
Thank you - see my other note in your email. I did tell AARP that we're closing in but also offered them equal value for some ad campaign during the legislative session, so they know there's risk.

That said - the longer it takes to get this out, the more ridiculous we look releasing it. We really need responses - time to respond - to make it valuable.

**Comment by mzagaja** [comment]
Figured it out this morning (coding is 100x easier with a fresh brain). My script now works as far as I can tell. Not sure why these two candidates below have duplicate e-mails so might want to poke in the app on that and see who they are duplicate with. (You can take a peek at them in RailsAdmin panel if you want to do it yourself). I think all systems are ready to go. I should be able to launch the e-mail to candidates when I get home tonight.

Falcon to ground control, requesting permission to begin liftoff 😉.
```
Validation failed: Email has already been taken
#<Candidate id: 242, candidate_name: "James Lynch", party: "Republican", cep_status: nil, website: nil, district_id: 91, created_at: "2016-10-28 12:23:38", updated_at: "2016-10-28 12:23:38", candidate_email: "lynch91st@yahoo.com", committee_email: nil, headshot_file_name: nil, headshot_content_type: nil, headshot_file_size: nil, headshot_updated_at: nil, q1: nil, q2: nil, q3: nil, q4: nil, user_id: nil, q5: nil, q6: nil, q7: nil, q8: nil, q9: nil, age: nil, marital_status: nil, current_town_residence: nil, current_job: nil, previous_job: nil, previous_job2: nil, education: nil, facebook: nil, twitter: nil, instagram: nil, snapchat: nil, periscope: nil>
Validation failed: Email has already been taken
#<Candidate id: 309, candidate_name: "Ronna Stuller", party: "Green Party", cep_status: "nonparticipating", website: nil, district_id: 39, created_at: "2016-10-28 12:23:39", updated_at: "2016-10-28 12:23:39", candidate_email: "rstuller@snet.net", committee_email: nil, headshot_file_name: nil, headshot_content_type: nil, headshot_file_size: nil, headshot_updated_at: nil, q1: nil, q2: nil, q3: nil, q4: nil, user_id: nil, q5: nil, q6: nil, q7: nil, q8: nil, q9: nil, age: nil, marital_status: nil, current_town_residence: nil, current_job: nil, previous_job: nil, previous_job2: nil, education: nil, facebook: nil, twitter: nil, instagram: nil, snapchat: nil, periscope: nil>
```

**Comment by doughardy-ctnj** [comment]
Fantastic - so the same email for 2 campaigns? I suppose that's possible. I
should reach out to see if it's a mistake

**Comment by mzagaja** [comment]
Yeah I'd check in the admin panel login to see what it's duplicative with and then also see if there are empty ones that we need/want to manually populate with addresses before we fire it off. Also forgot to ask: did we settle on a from address for the e-mail yet? Still using your doughardy gmail one.

**Comment by doughardy-ctnj** [comment]
it'll be vote@ctnewsjunkie.com

where's the RailsAdmin panel? I

**Comment by doughardy-ctnj** [comment]
so there are 2 duplicates right? meaning there are 4 candidates under 2 emails?
lynch91st@yahoo.com
and
rstuller@snet.net

**Comment by mzagaja** [comment]
Yep. If you can't find them I can probably take a look at lunch time. 

-Matt

**Comment by doughardy-ctnj** [comment]
Search for lynch email comes up with 2 users under District #91:

https://vote.ctnewsjunkie.com/admin/candidate?model_name=candidate&utf8=%E2%9C%93&query=lynch91st%40yahoo.com

Same with Stuller email, District #39:

https://vote.ctnewsjunkie.com/admin/candidate?model_name=candidate&utf8=%E2%9C%93&query=rstuller%40snet.net

only difference in Lynch and Stuller's two user accounts appears to be one says yes on CEP, the other does not

Otherwise they are identical - may just need to delete the extra ones

**Comment by doughardy-ctnj** [comment]
Stuller shows up twice on the front-facing page for District 39:
https://vote.ctnewsjunkie.com/districts/39

and so does Lynch on 91:
https://vote.ctnewsjunkie.com/districts/91

I think we just need to delete a pair of users

**Comment by mzagaja** [comment]
Ah ok. Must be have been duped in the original file from SEEC. 

-Matt

**Comment by doughardy-ctnj** [comment]
i will delete

**Comment by doughardy-ctnj** [comment]
Everything seems OK - I'm going to check for missing email addresses first, and I'd like to test the email invite and form-fill process once more tonight before we send the mass email. 

I'm assuming we don't need to cut over any domains or anything of that sort - nothing is aimed at the hero stuff rather than vote.ctnewsjunkie.com

**Comment by mzagaja** [comment]
Yep everything is live and points to the vote.ctnewsjunkie.com domain. Will plan to test an email send from the live server when I get back tonight and then maybe we can launch the email to the candidates around 7 or 8? 

-Matt

**Comment by doughardy-ctnj** [comment]
Yeah that sounds good - I may be crunching a bit on our radio project during that time, but will try to get everything in place so we can test without distractions
