### ISSUE TITLE
Setup SendGrid + Admin E-Mail

### ISSUE THREAD

**Issue by mzagaja** [mzagaja/ctnewsjunkie_voterguide#5]
I will need an admin e-mail that all the account e-mails can come from to setup SendGrid. Let me know what you want me to use.

**Comment by doughardy-ctnj** [comment]
I'm not sure what you mean, do you need me to create an email address of some kind?

**Comment by mzagaja** [comment]
It can be any e-mail address (i.e. ctnewsjunkie@gmail.com) but this e-mail address will be the e-mail address that the users see the account e-mails coming from so you'll want it to be one that you can receive e-mails at so you can deal with questions/issues if people reply. I wasn't sure if you had a special website e-mail address you use for this sort of thing.

**Comment by doughardy-ctnj** [comment]
i don't have anything really - just go with doughardy.ojp@gmail.com and we should be all set

**Comment by mzagaja** [comment]
Will do!
