### ISSUE TITLE
Setup User Authentication and Authorization with Pundit

### ISSUE THREAD

**Issue by mzagaja** [mzagaja/ctnewsjunkie_voterguide#6]
Right now it's a free for all. We'll need to setup Pundit and Devise to work with Rails Admin and the rest of the app to make sure nobody who we don't want to be in the app gets in.

**Comment by doughardy-ctnj** [comment]
Can you fill me in on whether we're making an app, that people will have to download, or a website that uses an app in the background?

**Comment by mzagaja** [comment]
I guess the best way to describe it is this is a web application in the way WordPress is.

**Comment by doughardy-ctnj** [comment]
OK thanks
