### ISSUE TITLE
Outreach to Major Parties

### ISSUE THREAD

**Issue by doughardy-ctnj** [mzagaja/ctnewsjunkie_voterguide#63]
Towns we have from SEEC:

Cheshire
Colchester
East Haddam
East Haven
Hamden
Killingworth
Manchester
Meriden
Middletown
Monroe
New Britain
New Hartford
Norwich
Pomfret
Scotland
Simsbury
Stonington
Trumbull
West Hartford
Westport

**Comment by doughardy-ctnj** [comment]
Matt - I think I should send a spreadsheet to the party chairmen for the Dems, Reps, Green and WFP and anyone else who is capable of filling out their slate. Maybe the local committee chairs as well?

In terms of what should be on the spreadsheet - should I send them the SEEC spreadsheet as is (deleting other candidates info for the 20 towns) ... maybe I would leave the towns we need in the Municipality column?

**Comment by doughardy-ctnj** [comment]
I have shared via slack the spreadsheet we might consider sending - but I'm concerned about how we'll handle this. 

Let's say the state party chairman each provide us with a separate spreadsheet - that would be ideal. We could collate something like that easily.

But if we have to get one for each party from each town's specific town committee chair ... that could be challenging (though doable). 

Would it be smarter to do a google doc for each party and have them all fill in the same doc?

**Comment by doughardy-ctnj** [comment]
Have sent sheet to WFP only so far.

**Comment by doughardy-ctnj** [comment]
Have send the sheet to GOP and Dems as well.

**Comment by mzagaja** [comment]
Doug, I think doing one shared Google spreadsheet for each party is a good approach.
