### ISSUE TITLE
Branding image includes 2016

### ISSUE THREAD

**Issue by doughardy-ctnj** [mzagaja/ctnewsjunkie_voterguide#64]
Need to replace branding images

**Comment by mzagaja** [comment]
Do you have a new one from your shuttershock or whatever you want me to use?

**Comment by doughardy-ctnj** [comment]
Where does that image appear for branding? On social media sharing only? 

Also, with the municipal district shape map, is there a statewide image of that map or does it just exist as data?

**Comment by doughardy-ctnj** [comment]
![connecticut-election-district-map-uconn-2010](https://user-images.githubusercontent.com/22284125/30250596-f7ad3992-961e-11e7-87eb-dbc93ff50c2a.jpg)

**Comment by mzagaja** [comment]
I think you are referring to the banner at the top of the main page, right? That image only appears when folks visit the site itself. We were using the CT Capitol for the social media sharing.

**Comment by doughardy-ctnj** [comment]
I don't know if the red-squiggly lines of the voting districts really do us any favors. will give this more thought today.

**Comment by doughardy-ctnj** [comment]
![stock-photo-man-putting-ballot-in-a-box-during-elections-in-front-of-flag-american-state-of-connecticut-92686144](https://user-images.githubusercontent.com/22284125/30302986-ec21ecca-9732-11e7-90a5-05ea5268d4f6.jpg)

**Comment by doughardy-ctnj** [comment]
![stock-photo-voting-concept-ballot-box-with-national-flag-on-background-connecticut-233424247](https://user-images.githubusercontent.com/22284125/30303020-2ffec42c-9733-11e7-97ca-c5d52ffb4de3.jpg)

**Comment by doughardy-ctnj** [comment]
Let's go with this one - what size do we need it to be?
![vote-connecticut-shutterstock_92686144-2000](https://user-images.githubusercontent.com/22284125/30331748-9744fc1e-97a6-11e7-8bdb-62aee8d4058b.jpg)

**Comment by mzagaja** [comment]
1170x90. Follow same format as current background image:

![header-background](https://user-images.githubusercontent.com/565647/30409432-efbb067c-98d2-11e7-8f7f-b98e8596628a.jpg)

Did you want to change the social graph picture as well? That one is 1200x630.

**Comment by doughardy-ctnj** [comment]
Was only concerned about social, because it was the capitol

**Comment by doughardy-ctnj** [comment]
![vote-ctnewsjunkie-header-image-no-year](https://user-images.githubusercontent.com/22284125/31461010-24653310-ae96-11e7-8fa7-1da9bad152b9.jpg)
