### ISSUE TITLE
Setup SendGrid and DotEnv Gems

### ISSUE THREAD

**Issue by mzagaja** [mzagaja/ctnewsjunkie_voterguide#7]
https://sendgrid.com/docs/Integrate/Frameworks/rubyonrails.html is how to setup SendGrid for production e-mails for user accounts, etc.

**Comment by doughardy-ctnj** [comment]
This is for inviting a specific list of candidates and/or their campaign managers, correct?

**Comment by mzagaja** [comment]
This issue is specific to sending e-mails but you're right we should have an issue to discuss how we are going to invite everyone into the app and what classes of users will exist, etc. Do you want to start a new issue for user types and how to handle them?

**Comment by doughardy-ctnj** [comment]
sure
