### ISSUE TITLE
New ad code

### ISSUE THREAD

**Issue by doughardy-ctnj** [mzagaja/ctnewsjunkie_voterguide#76]
At the moment the AARP ad is serving with code specific to the ad itself. 

I would like to replace that with a script for an ad zone to which we can assign multiple ad campaigns without opening up the vote app.

Here's the instructs in a screengrab:
![screen shot 2017-10-09 at 12 26 00 am](https://user-images.githubusercontent.com/22284125/31325221-8c6d2568-ac88-11e7-9b0f-8f83d01c14cd.png)

Here's the two scripts:
<script src="https://cdn.broadstreetads.com/init-2.min.js"></script>
<script>broadstreet.watch({ networkId: 15 })</script>

and

<broadstreet-zone zone-id="61766"></broadstreet-zone>

NOTE: The same ad is serving in the new zone, so don't be surprised when you see AARP pop up again.

No response from Ben Berkowitz yet. Will try him again.

**Comment by doughardy-ctnj** [comment]
Have discovered that the old ad code is still showing on the candidate pages

**Comment by mzagaja** [comment]
Ad code had to be updated in separate (but nearly identical) layout template for candidate pages. Will hopefully remember next time!
