### ISSUE TITLE
Odd search failure

### ISSUE THREAD

**Issue by doughardy-ctnj** [mzagaja/ctnewsjunkie_voterguide#78]
In the Ruby app, when I search for in Candidates for Danbury, only one of the 4 WFP candidates from Danbury comes up - Paul Sutherland. He filled out his information. The other 3 don't come up in the list. Just the new Dems we loaded and Paul Sutherland.

**Comment by doughardy-ctnj** [comment]
In the District section, a search for Danbury turns up 23 results (all of them).

**Comment by mzagaja** [comment]
Hey sorry I missed this. My understanding (which now sounds incorrect) from our conversation had been that we already put in the WFP candidates from a previous import so I removed them from the Danbury list so we didn't import them twice. If they do need to be pulled in, I'll do it tonight.
