### ISSUE TITLE
Obtain Raw Candidate Data

### ISSUE THREAD

**Issue by mzagaja** [mzagaja/ctnewsjunkie_voterguide#8]
We need to obtain the raw candidate data and then appropriately plan for how to hold it in the app. This thread is to discuss what we need to get and how.

**Comment by doughardy-ctnj** [comment]
We can either get it from the SOTS's office or attempt to use the Voatz API, correct?

**Comment by mzagaja** [comment]
Does this look accurate? It's from http://www.ct.gov/seec/cwp/view.asp?a=3548&q=430038. If we need more information you will have to ask the SotS office for a more detailed spreadsheet if they have it or source it elsewhere. My general sense is I will likely just have candidates have a "name" field instead of "first_name" and "last_name" since some of them have middle names, etc. and I don't think we need to separate them for our purposes right now. Let me know if this looks sufficient and if you want me to include anything other than the name and district.


[Candidate Registration List for Election Year 2016.pdf](https://github.com/mzagaja/ctnewsjunkie_voterguide/files/479922/Candidate.Registration.List.for.Election.Year.2016.pdf)

**Comment by mzagaja** [comment]
Just bumping this for a response to above @doughardy-ctnj

**Comment by doughardy-ctnj** [comment]
I'm sorry for the delay - this will have to do for the 1.0 version. I don't
know that they would add anything beyond what's required by law.
