### ISSUE TITLE
Editing survey response show serious security problem

### ISSUE THREAD

**Issue by doughardy-ctnj** [mzagaja/ctnewsjunkie_voterguide#84]
So when I created my own user and logged out of everything, cleared history and cache, opened the survey link in a private window... I was able to edit and update the responses.

[https://vote.ctnewsjunkie.com/survey_responses/91](https://vote.ctnewsjunkie.com/survey_responses/91)

So we have maybe 3 people who have requested the option to edit their responses - I have thus far pasted their responses into an email and asked them to delete the ones they will leave the same and to edit the ones they want changed, and to email them back.

I wouldn't want any actual candidate to figure out that their survey responses aren't secure if the link gets out.

**Comment by mzagaja** [comment]
Fixed this.
