### ISSUE TITLE
Photo refuses to change

### ISSUE THREAD

**Issue by doughardy-ctnj** [mzagaja/ctnewsjunkie_voterguide#86]
[https://vote.ctnewsjunkie.com/candidates/421](https://vote.ctnewsjunkie.com/candidates/421)

I have loaded larger version of this guy's image over and over, with different files names. I have even loaded a 1x1 pixel, and then reloaded a larger version of the original photo - regardless of what I do, the smaller version of the image continues to display and it's too small to be recognized on social media. 
:-/
![large-ben-wenograd-large](https://user-images.githubusercontent.com/22284125/31872180-8dc66ad2-b787-11e7-9048-0ffa560109c3.png)

![large-ben-wenograd-large 1](https://user-images.githubusercontent.com/22284125/31872210-d567bada-b787-11e7-80fe-db3facb8ca3c.png)

**Comment by mzagaja** [comment]
I think it is because the ratio is a landscape photo. You might need to crop the sides to get the right ratio to make it big enough. Otherwise I am not sure.
