### ISSUE TITLE
Fairfield Democrats Import errors

### ISSUE THREAD

**Issue by doughardy-ctnj** [mzagaja/ctnewsjunkie_voterguide#87]
We imported a list of 65 but on show 62 - here's why:

Ruth Smey and Jay Wolk are each listed twice, once for Constable and once for RTM 05.

Jennifer Jacobsen and Jennifer Leeper are both WFP endorsees, so they were both already in the system.

Dru Georgiadis ran for the state legislature last year, so her 2017 candidacy dropped off.

[Vote-CTNewsJunkie-List-Form-For-Fairfield-Democrats-dh-edited.xlsx](https://github.com/mzagaja/ctnewsjunkie_voterguide/files/1416475/Vote-CTNewsJunkie-List-Form-For-Fairfield-Democrats-dh-edited.xlsx)

**Comment by doughardy-ctnj** [comment]
Can multiple districts be added to one candidate? That would seem to be the way to go, adding the additional office to each one.

I'm not sure how to handle the issue with Georgiadis - maybe remove the email from her previous election? Not sure.

**Comment by mzagaja** [comment]
Since candidates can run in multiple races we need to allow multiple candidate profiles per user now.

Also I should update the import script to allow duplicate candidate emails.

**Comment by doughardy-ctnj** [comment]
will be important to keep them associated with specific elections
