### ISSUE TITLE
Setup Production Server

### ISSUE THREAD

**Issue by mzagaja** [mzagaja/ctnewsjunkie_voterguide#9]
This thread is for production server setup issues, likely to be worked on next weekend.

We'll need to get vote.ctnewsjunkie.com or some other subdomain to point to our server once it is live. This will be done by going to the domain registrar and having it's "A record" point to the IP address of our Linode once it is live.

**Comment by doughardy-ctnj** [comment]
I can add a subdomain any time

**Comment by mzagaja** [comment]
@doughardy-ctnj I began setup of the server. Please point a subdomain (vote.ctnewsjunkie.com?) to 104.200.28.136

**Comment by doughardy-ctnj** [comment]
Having connectivity issue - can you wait?

**Comment by doughardy-ctnj** [comment]
Lon are you able to help out with this - I'm having connectivity issues at
the conference. Matt needs a subdomain pointed at that voter guide project.
I think it needs to be done in nexcess and for some reason i'm struggling
to call it up - I believe you have access?

*Doug Hardy*
Business Manager, Dig and Scoop LLC dba CTNewsJunkie.com
<http://ctnewsjunkie.com/>
Co-Founder/New Media Developer for Independent Media Network LLC
<http://imnct.com/>
(860) 543-9453 (mobile)

**Comment by mzagaja** [comment]
Sure it's not specifically urgent. I can work on other things in the mean time.

**Comment by doughardy-ctnj** [comment]
I don't think I have nexcess access I can check if I have a password
somewhere

**Comment by mzagaja** [comment]
Ok the production server is now live at vote.ctnewsjunkie.com but still needs the seed data setup.

**Comment by doughardy-ctnj** [comment]
Look great. Have you thought about scrapping social media for images? P2A
is doing that but there are a lot of people with the same names I'm sure.
Official pol pages may be available by api.

**Comment by mzagaja** [comment]
Social media scraping, etc. for images will likely be a 0.2 issue. Since this is up and working I'm going to close this specific issue and accept the other suggestion as a new issue.
