### ISSUE TITLE
Question logos and disclaimers

### ISSUE THREAD

**Issue by doughardy-ctnj** [mzagaja/ctnewsjunkie_voterguide#90]
I know it might be difficult to accomplish but the "universality" of the logos next to the questions is problematic. As is the disclaimer language if it mentions sponsors in an identifiable way and changes from one election to the next. I think we need blanket disclaimer language to solve that part.

But right now the CTNJ logo appears next to all questions based on the fact that we had no sponsors in 2017. CTNJ is next to the questions that had been sponsored by AARP in 2016. And in 2018 if we get other sponsors... *their* logo may appear next to a previous AARP questions.

**Comment by mzagaja** [comment]
Code for this is located in app/views/candidates/show.html.erb:90-99. We already put the information on sponsors in the database so we just need to add code in the view to show the appropriate logo based on the sponsor.
