### ISSUE TITLE
Geo

### ISSUE THREAD

**Issue by doughardy-ctnj** [mzagaja/ctnewsjunkie_voterguide#96]
I’m not certain but I think my location for the house district button is showing me in windsor while the senate shows east haddam. Google maps has me in west hartford.

**Comment by mzagaja** [comment]
Open States reversed how the geography lands. I just had to switch where it looked. Should be fixed on staging now, try it again and let me know.

**Comment by doughardy-ctnj** [comment]
Works! Can close
